name: CivilizedandSavage
favicon: null
layout_spectrum: 0.49452
typography_spectrum: 0.88644
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: A website for those who live on both sides of the coin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0b0b0b'
    - '#171717'
    - '#a1141c'
    - '#232323'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
