favicon: null
layout_spectrum: 0.6003584
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.7939068
  lightness: 0.7849463
  brandColors:
    - '#FFFFFF'
    - '#808080'
    - '#323232'
    - '#F96E5B'
    - '#1E051F'
  rhythmicContrast: 0.6505376
typography_spectrum: 0.7939068
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: CivilizedandSavage
